Vagrantfile

#79: Vagrantfile, add file

---

puppet/manifests/default.pp

#80: Implement puppet manifest 'default.pp'

---

.gitignore

#85: .gitignore, ignore '.vagrant/'

---

puppet/manifests/default.pp

#87: Allow 'phpMyAdmin' access from VM guest to host

---

puppet/manifests/default.pp

#87: default.pp, fix typo, adjust dockblocks

---

puppet/manifests/default.pp

#87: default.pp, increase timeout, fix comment

---

config/enable_modules.py

#82: enable_modules.py, python-drush for modules

---

config/enable_modules.py

#82: enable_modules.py, fix typo

---

config/enable_themes.py

#93: enable_themes.py, add script

---

config/enable_configs.py
puppet/manifests/default.pp

#98: Implement Drupal Clean URLs in Centos 6.6

---

puppet/manifests/default.pp

#98: default.pp, fix typo

---

puppet/manifests/default.pp

#80: default.pp, create symlink correctly

---

puppet/manifests/default.pp

#80: default.pp, revert symlink

---

puppet/manifests/default.pp

#106: default.pp, replace symlink with docroot definition

---

puppet/manifests/default.pp

#108: Allow '.htaccess' by modifying 'httpd.conf'

---

puppet/manifests/default.pp

#108: default.pp, adjust comments

---

puppet/manifests/default.pp

#108: default.pp, remove quotes for '.htaccess' logic

---

puppet/manifests/default.pp

#108: default.pp, replace 'AllowOverride None'

---

puppet/manifests/default.pp

#108: default.pp, fix minor typo

---

puppet/manifests/default.pp

Define timezone with 'default.pp'

---

.htaccess
error.php
puppet/manifests/default.pp

#117: Define HTTP Errors in '.htaccess', and 'httpd.conf'

---

puppet/manifests/default.pp

#117: Correctly remove comments in 'httpd.conf'

---

Vagrantfile

#126: Enable Vagrant SSL port forwarding

---

Vagrantfile
puppet/manifests/ssl.pp

#124: Automate SSL Certificate generation in 'default.pp'

---

puppet/manifests/ssl.pp

#123: ssl.pp, adjust 'cname' to 'localhost'

---

Vagrantfile
puppet/manifests/default.pp

#148: Error: Could not parse application options

---

Vagrantfile

#150: Vagrantfile, add 'vagrant-r10k' plugin

---

puppet/Puppetfile

#152: Puppetfile, add 'stdlib' puppet module

---

puppet/Puppetfile

#152: Puppetfile, minor language change

---

Vagrantfile

#152: Vagrantfile, add 'r10k' implementation

---

Vagrantfile

#152: Vagrantfile, allow 'Puppetfile' to install 'stdlib'

---

puppet/Puppetfile

#152: Puppetfile, remove 'stdlib'

---

puppet/Puppetfile
puppet/manifests/default.pp

#146: Upgrade default Centos 6.6 PHP 5.3.3 to PHP 5.6

---

puppet/Puppetfile

#145: Puppetfile, add 'vcsrepo' puppet module

---

.gitignore

#147: .gitignore, ignore '/log/' directory

---

Vagrantfile
puppet/manifests/theme_bootstrap.pp

#143: Install Bootstrap Theme

---

puppet/manifests/theme_bootstrap.pp

#143: theme_bootstrap.pp, adjust 'before' attribute

---

.gitignore

#167: .gitignore, add '/sites/all/thems/contib/'

---

.htaccess

#144: .htaccess, block access to 'build.txt'

---

build.txt
puppet/manifests/default.pp

#144: Implement Varnish

---

puppet/manifests/default.pp

#142: default.pp, increase php memory limit

---

puppet/manifests/default.pp

#142: default.pp, fix unterminated syntax error

---

puppet/manifests/default.pp

#140: default.pp, add opcache installation

---

puppet/manifests/default.pp

#140: default.pp, remove 'refreshonly' attribute

---

puppet/manifests/default.pp

#140: default.pp, add 'before' attribute for 'opcache'

---

puppet/manifests/default.pp

#140: default.pp, update 'package' attributes

---

puppet/manifests/default.pp

#140: default.pp, adjust 'before', and 'notify' attributes

---

puppet/Puppetfile

#182: Puppetfile, add 'nodejs' puppet module

---

puppet/Puppetfile

#182: Add 'nodejs' module dependencies

---

puppet/Puppetfile

#182: Puppetfile, add 'wget' puppet module

---

puppet/Puppetfile

#182: Puppetfile, add 'puppet-gpg_key' puppet module

---

puppet/Puppetfile

#192: Puppetfile, adjust url references

---

puppet/Puppetfile

#192: Puppetfile, remove unnecessary syntax

---

.gitignore

#198: .gitignore, ignore 'asset' directory

---

drush/core_update2.py

#203: python-drush script, update core ignore files

---

drush/core_update.py
drush/core_update2.py

#203: update docblocks for core update drush script

---

Vagrantfile

#208: Implement Centos 7.x in 'Vagrantfile'

---

Vagrantfile

#217: Vagrantfile, remove 'box_version'

---

.gitignore

#222: Adjust '.gitignore' relative to directory restructuring

---

Vagrantfile
puppet/environment/development/Puppetfile
puppet/environment/development/manifests/setup_database.pp

#224: Move database logic to 'setup_database.pp'

---

puppet/environment/development/manifests/setup_database.pp

#226: setup_database.pp, fix typo

---

puppet/environment/development/manifests/setup_database.pp

#228: setup_database.pp, remove '::mysql::client'

---

puppet/environment/development/manifests/default.pp

#230: default.pp, remove 'service mysqld start'

---

puppet/environment/development/manifests/default.pp

#232: Remove 'chkconfig mysqld on' within 'default.pp'

---

puppet/environment/development/manifests/default.pp

#234: Replace iptables with firewalld implementation

---

puppet/environment/development/manifests/default.pp

#236: Restart firewalld instead of iptables

---

puppet/environment/development/manifests/default.pp

#236: default.pp, adjust puppet typos, reference 'firewalld'

---

contributing.md

#221: Add 'contributing.md'

---

puppet/environment/development/manifests/default.pp

#241: Remove 'service mysqld restart' from 'default.pp'

---

puppet/environment/development/Puppetfile

#251: Update modules, add proper extensions 'Puppetfile'

---

puppet/environment/development/Puppetfile

#253: Puppetfile, replace double quotes with single quotes

---

puppet/environment/development/scripts/imagemin
puppet/environment/development/scripts/sass
puppet/environment/development/scripts/uglifyjs

#210: Update webcompiler bash scripts

---

puppet/environment/development/manifests/compile_asset.pp
puppet/environment/development/manifests/default.pp

#248: Replace upstart with systemd in 'compile_asset.pp'

---

Vagrantfile
puppet/environment/development/Puppetfile
puppet/environment/development/manifests/configure_php.pp
puppet/environment/development/manifests/default.pp

#249: Move php logic into 'configure_php.pp'

---

puppet/environment/development/manifests/setup_database.pp

#258: Implement php-mysql bindings in 'setup_database.pp' 

---

puppet/environment/development/manifests/compile_asset.pp
puppet/environment/development/template/webcompilers.erb

#257: Implement puppet template for systemd compiler logic

---

puppet/environment/development/manifests/configure_php.pp

#266: configure_php.pp, properly append after line match

---

puppet/environment/development/manifests/compile_asset.pp

#268: Fix systemd webcompiler template path

---

puppet/environment/development/manifests/compile_asset.pp

#268: compile_asset.pp, fix path for webcompilers

---

puppet/environment/development/manifests/compile_asset.pp

#268: compile_asset.pp, correctly implement puppet variable

---

puppet/environment/development/manifests/compile_asset.pp

#273: compile_asset.pp, fix path for webcompiler

---

puppet/environment/development/manifests/default.pp
puppet/environment/development/manifests/ssl.pp

#264: Adjust 'httpd' service with systemd / puppet syntax

---

drush/core_update2.py

#282: Update variables within 'core_update2.py'

---

Vagrantfile

#284: Vagrantfile, add 'forwarded_port' rules

---

puppet/environment/development/manifests/configure_database.pp

#286: Grant 'CREATE', and 'DROP' privileges

---

puppet/environment/development/manifests/configure_php.pp

#288: Allow 'phpMyAdmin' web access

---

puppet/environment/development/manifests/configure_compilers.pp

#290: Remove portion of docblock

---

.gitignore

#292: Remove unnecessary entries from '.gitignore'

---

puppet/environment/development/manifests/configure_database.pp

#296: Grant 'ALTER' sql permission to 'authenticated' user

---

drush/core_update.py

#304: Adjust docblock within 'core_update.py'

---

puppet/environment/development/manifests/configure_php.pp

#294: Install, and enable opcache

---

puppet/environment/development/scripts/sass

#309: Fix 'scss' source / asset paths in 'sass' bash script

---

puppet/environment/development/scripts/imagemin

#310: Fix 'img' source / asset paths in 'imagemin' bash script

---

puppet/environment/development/scripts/uglifyjs

#311: Fix 'js' source / asset paths in 'uglifyjs' bash script

---

puppet/environment/development/scripts/sass

#315: Ensure scss partials does not get compiled with sass

---

license.md

#306: Add 'license.md'

---

license.md

#306: license.md, revert repo name to name

---

Vagrantfile
src/default/default.settings.php
webroot/sites/default/files/README.md

#323: Define shared '/vagrant' permission, and ownership

---

Vagrantfile

#326: Ensure 'apache' user owns 'sites/default/' directory

---

puppet/environment/development/manifests/configure_httpd.pp

#333: Set ownership, restore system context on 'httpd.conf'

---

puppet/environment/development/manifests/configure_php.pp

#335: Use current user home directory in 'configure_php.pp'

---

puppet/environment/development/manifests/configure_php.pp

#337: Dynamic pathing, restore context on 'phpMyAdmin.conf'

---

puppet/environment/development/manifests/configure_php.pp

#337: Further implement 'working_dir' in 'configure_php.pp'

---

Vagrantfile

#325: Allow 'sites/default/' to 664 permission from 'Vagrantfile'

---

puppet/environment/development/manifests/configure_drush.pp

#342: Ensure drush is properly aliased 'configure_drush.pp'

---

README.md

#239: Create 'README.md'

---

contributing.md

#345: Create 'contributing.md

---

README.md

#347: Fix some typos in the intro 'README.md'

---

contributing.md

#349: Update links within 'contributing.md'

---

puppet/environment/development/Puppetfile

#355: Add 'puppet-firewalld' to 'Puppetfile'

---

README.md

#359: Add sql info to Installation section of 'README.md'

---

puppet/environment/development/manifests/configure_drush.pp
puppet/environment/development/manifests/configure_httpd.pp

#352: Configure httpd to allow drupal 'clean_url'

---

Vagrantfile

#298: Ensure 'vagrant destroy' deletes 'settings.php'

---

puppet/environment/development/manifests/configure_database.pp

#366: Implement class wrappers for 'configure_database.pp'

---

puppet/environment/development/manifests/configure_database.pp

#366: configure_database.pp, remove 'require' attribute

---

Vagrantfile

#374: Do not remove 'site/default/files/README.md'

---

puppet/environment/development/manifests/configure_compilers.pp

#367: Implement class wrappers for 'configure_compilers.pp'

---

README.md

#88: Add 'phpMyAdmin' in 'README.md'

---

puppet/environment/development/manifests/configure_compilers.pp

#380: Properly define 'before' in 'configure_compilers.pp'

---

README.md

#216: Create 'README.md' for drush update script

---

puppet/environment/development/template/webcompilers.erb

#385: Ensure webcompilers use 'provisioner' user

---

puppet/environment/development/Puppetfile
puppet/environment/development/manifests/configure_compilers.pp
puppet/environment/development/manifests/configure_httpd.pp
puppet/environment/development/manifests/configure_php.pp
puppet/environment/development/scripts/imagemin
puppet/environment/development/scripts/sass
puppet/environment/development/scripts/uglifyjs

#368: Implement class wrappers for 'configure_php.pp'

---

Vagrantfile
puppet/environment/development/template/webcompilers.erb

#387: Webcompilers systemd *.service failed

---

puppet/environment/development/manifests/configure_httpd.pp
puppet/environment/development/template/webcompilers.erb

#128: Include HTTP 400 error in virtualhost

---

centos7x/selinux/README.md
centos7x/stig/README.md

#392: Add 'README.md' for selinux

---

centos7x/selinux/README.md

#392: README.md, link text for selinux

---

puppet/environment/development/manifests/configure_httpd.pp

#395: ErrorDocument prints filename

---

.gitignore
puppet/environment/development/manifests/stig.pp

#397: Create skeleton 'stig.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_010270.pp
puppet/environment/development/modules/high/manifests/rhel_07_020220.pp

#401: Create 'rhel_07_010270.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_040590.pp

#404: Create 'rhel_07_040590.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_020000.pp

#406: Create 'rhel-07-020000.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_020000.pp
puppet/environment/development/modules/high/manifests/rhel_07_040330.pp

#408: Create 'rhel_07_040330.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_010260.pp

#410: Create 'rhel_07_010260.pp'

---

puppet/environment/development/modules/high/manifests/rhel_07_040590.pp

#412: Replace 'file_line' with 'sed' in 'rhel_07_040590.pp'

---

puppet/environment/development/modules/high/manifests/rhel_07_040590.pp

#415: Add path for 'sed' in 'rhel_07_040590.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_021910.pp

#414: Create 'rhel-07-021910.pp'

---

puppet/environment/development/modules/high/manifests/rhel_07_040590.pp

#419: Generalize '/etc/ssh/sshd_config' in 'rhel_07_040590.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_040580.pp

#418: Create 'rhel_07_040580.pp'

---

puppet/environment/development/modules/high/manifests/rhel_07_010270.pp

#422: Remove 'PermitEmptyPasswords'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_040500.pp

#424: Create 'rhel_07_040500.pp'

---

.travis.yml
README.md

#426: Implement scss linting

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/high/manifests/rhel_07_020010.pp

#431: Create 'rhel_07_020010.pp'

---

puppet/environment/development/manifests/stig.pp
puppet/environment/development/modules/medium/manifests/rhel_07_010440.pp

#434: Create 'rhel_07_010440.pp'

---

puppet/environment/development/manifests/configure_httpd.pp

#437: Implement 'allow_override' in 'configure_httpd.pp'

---

puppet/environment/development/modules/virtual_resource/manifests/file_gshadow.pp

#439: Define 'virtual resource' module for '/etc/gshadow'

---

puppet/environment/development/modules/virtual_resource/manifests/file_grub.pp
puppet/environment/development/modules/virtual_resource/manifests/file_grub_cfg.pp
puppet/environment/development/modules/virtual_resource/manifests/file_grub_d.pp

#442: Create virtual resource files for bootloader files

---

puppet/environment/development/modules/virtual_resource/manifests/file_audit_log.pp

#444: Create virtual resource files for '/var/log/audit/audit.log'

---

puppet/environment/development/Puppetfile
puppet/environment/development/manifests/configure_php.pp

#453: Implement 'inifile' module in 'configure_php.pp'

---

puppet/environment/development/manifests/configure_httpd.pp

#450: Add 'mod_headers' module for puppet apache

---

.travis.yml
Dockerfile

#447: Fix '.travis.yml' docker definition

---

puppet/environment/development/manifests/configure_php.pp

#462: Update 'epel-release' build required for php

---

README.md
Vagrantfile
puppet/environment/development/manifests/install_drupal.pp
puppet/environment/development/modules/drupal/manifests/install.pp

#464: Automate drupal build via 'drush make' or equivalent

---

puppet/environment/development/modules/drupal/manifests/install.pp
webroot/profiles/sample/sample.info
webroot/profiles/sample/sample.install
webroot/profiles/sample/sample.profile

#471: Implement drupal install profile

---

README.md
puppet/environment/development/modules/redis/manifests/start.pp

#477: Redirect redis standard output to log file

---

README.md

#484: Add vbox extension pack to 'README.md'

---

puppet/environment/development/modules/package/manifests/redis.pp

#486: Add 'timeout' for 'redis.pp'

---

puppet/environment/development/modules/redis/manifests/configure.pp

#488: Ensure redis systemd script has '770' mode

---

puppet/environment/development/manifests/configure_php.pp

#490: Increase 'timeout' for 'yum update' in 'configure_php.pp'

---

README.md

#492: Fix Typo under the PHPMyadmin bit on the code tab

---

README.md

#469: Ensure Travis status predicated on master branch

---

drush/core_update.py

#496: Update 'core_update.py' to ensure consistent cwd

---

drush/core_update.py

#496: core_update.py, remove '-r' flag

---

puppet/environment/development/manifests/configure_php.pp

#500: configure_php.pp, changes epel release to v7-7

---

puppet/environment/development/modules/package/manifests/redis.pp

#497: redis.pp, add 'timeout' attribute

---

puppet/environment/development/manifests/configure_compilers.pp

#512: configure_compilers.pp, fix indentation

---

puppet/environment/development/modules/redis_server/manifests/configure.pp

#511: configure.pp, remove unnecessary 'file' directive

---

puppet/environment/development/modules/package/lib/facter/redis_version.rb

#530: Interpolate 'redis_verison' within 'redis_version.rb'

---

Vagrantfile
puppet/environment/development/manifests/configure_php.pp

#532: Remove GPG Key conflict in puppet build

---

puppet/environment/development/manifests/configure_httpd.pp

#534: Remediate GPG Key conflict in puppet build

---

Vagrantfile
puppet/environment/development/Puppetfile
puppet/environment/development/manifests/configure_system.pp

#159: Add 'timezone' puppet module

---

Vagrantfile
puppet/environment/development/Puppetfile
puppet/environment/development/manifests/configure_compilers.pp
puppet/environment/development/manifests/configure_system.pp

#543: Unable to install nodejs 5x during vagrant build

---

puppet/environment/development/scripts/imagemin
puppet/environment/development/scripts/sass
puppet/environment/development/scripts/uglifyjs

#538: Ensure more robust webcompilers

---

puppet/environment/development/modules/package/lib/facter/redis_version.rb

#552: Update 'redis_version.rb' by generalizing version

---

puppet/environment/development/modules/httpd/manifests/restart.pp
puppet/environment/development/modules/php/manifests/enable_rpm.pp
puppet/environment/development/modules/php/manifests/init.pp
puppet/environment/development/modules/php/manifests/install_php.pp
puppet/environment/development/modules/php/manifests/install_rpm.pp

#451: Implement puppet module to install php
